### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/website-kumquat#9]
**Go-live checklist**
- [x] Ensure all URLs are available in the new website (incl. redirects configured in `netlify.toml`)
- [ ] ~Merge `website-kumquat` repo incl. git history into `website` ([how-to](https://techtldr.com/git-merg-two-or-more-repositories-and-keeping-history/))~
- [ ] Netlify
  - [ ] ~Connect the `gitpod-website` project to the `website-kumquat` GitHub repo at "Build & deploy" -> "Build settings"~
  - [ ] ~Change the production branch to `main` at "Build & deploy" -> "Deploy contexts"~
  - [x] Add the www.gitpod.io custom domain to the `website-kumquat` project
- [ ] ~Trigger a deployment to production by merging #330~
  - [x] Manually trigger a deployment

**Post-launch checklist**
- [x] Smoke test all pages - ask everyone to help and post feedback as a new issue with the `prod-feedback` label
  - [x] Client-side routing and SSR
  - [x] Social previews
- [x] Check GA

**T+n days checklist**
- [ ] Notify the team about the upcoming repo name change. Local repos need a change to their `remote origin`
- [ ] Wait until all PRs in the `website-kumquat` repo are merged.
- [ ] Rename the old `website` repo to `website-v1.0`
- [ ] Rename `website-kumquat` to `website`
- [ ] Replace all occurrences of `website-kumquat` with `website`
- [ ] Re-connect the `gitpod-website` Netlify project to the new `website` GitHub repo
- [ ] Change visibility of the new `website` repo to public 🎉 
- [ ] Process the checklist at #148

**Comment by mikenikles** [comment]
Closing as we decided not to rename the repos.
